the.data = read.table("Forest718.txt")
the.data <- as.matrix(read.table("Forest718.txt"))
hist(the.data[,1])
hist(the.data[,2])
hist(the.data[,3])
hist(the.data[,4])
hist(the.data[,5])
hist(the.data[,6])
hist(the.data[,7])
hist(the.data[,8])
hist(the.data[,9])
hist(the.data[,10])
hist(the.data[,11])
hist(the.data[,12])
plot(the.data[,5], the.data[,13])
plot(the.data[,6], the.data[,13])
plot(the.data[,7], the.data[,13])
plot(the.data[,8], the.data[,13])